# Generated by Django 4.2.11 on 2024-04-07 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialProvider',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, db_column='user_social_provider_id', db_comment='유저 소셜 제공자 아이디', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='이름', max_length=32)),
                ('description', models.CharField(blank=True, db_comment='설명', max_length=64)),
            ],
            options={
                'db_table': 'T_user_social_provider',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='user_id', db_comment='유저 아이디', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_comment='이메일', max_length=254, unique=True)),
                ('social_id', models.CharField(blank=True, db_comment='소셜 아이디', max_length=64, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(db_comment='이름', max_length=32)),
                ('is_active', models.BooleanField(db_comment='활성 여부', default=True)),
                ('is_deleted', models.BooleanField(db_comment='삭제 여부', default=False)),
                ('is_admin', models.BooleanField(db_comment='관리자 여부', default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='삭제 일시', null=True)),
                ('is_agree_privacy', models.BooleanField(db_comment='개인정보 동의 여부', default=True)),
                ('is_agree_marketing', models.BooleanField(db_comment='마케팅 정보 수신 동의 여부', default=False)),
                ('gender', models.CharField(blank=True, db_comment='성별', max_length=1)),
                ('birth', models.DateField(blank=True, db_comment='생년월일')),
                ('phone_number', models.CharField(blank=True, db_comment='전화번호', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_social_provider', models.ForeignKey(db_comment='유저 소셜 제공자 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.usersocialprovider')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
