# Generated by Django 4.2.11 on 2024-04-08 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerpet_is_deleted'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_pet',
            field=models.ForeignKey(db_comment='고객 펫 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='customers.customerpet'),
        ),
    ]
