# Generated by Django 5.0.6 on 2024-05-10 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_kindergardens', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreservation',
            name='pet_kindergarden',
            field=models.ForeignKey(db_comment='펫 유치원 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='daily_reservations', to='pet_kindergardens.petkindergarden'),
            preserve_default=False,
        ),
    ]
