# Generated by Django 5.0.6 on 2024-06-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_dailyreservation_pet_kindergarden'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_extented',
            field=models.BooleanField(db_comment='고객 티켓 연장 여부', default=False),
        ),
    ]
