# Generated by Django 5.0.6 on 2024-06-07 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_dailyreservation_pet_kindergarden'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='depth',
            field=models.PositiveIntegerField(db_comment='노드 깊이', default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='parent',
            field=models.ForeignKey(db_comment='부모 예약 아이디', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reservations.reservation'),
        ),
    ]
