# Generated by Django 5.0.4 on 2024-05-07 08:06

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPetKindergarden',
            fields=[
                ('id', models.AutoField(auto_created=True, db_comment='펫 유치원 로우 아이디', primary_key=True, serialize=False)),
                ('thum_url', models.URLField(db_column='thumUrl', db_comment='썸네일 이미지')),
                ('tel', models.CharField(db_column='tel', db_comment='전화번호', max_length=16)),
                ('virtual_tel', models.CharField(blank=True, db_column='virtualTel', db_comment='가상 전화번호', max_length=16)),
                ('name', models.CharField(db_column='name', db_comment='이름', max_length=64)),
                ('x', models.DecimalField(db_column='x', db_comment='경도', decimal_places=6, max_digits=9)),
                ('y', models.DecimalField(db_column='y', db_comment='위도', decimal_places=6, max_digits=8)),
                ("business_start_hour", models.TimeField(db_comment="영업 시작 시간")),
                ("business_end_hour", models.TimeField(db_comment="영업 종료 시간")),
                ('address', models.CharField(db_column='address', db_comment='주소', max_length=128)),
                ('road_address', models.CharField(db_column='roadAddress', db_comment='도로명 주소', max_length=128)),
                ('abbr_address', models.CharField(db_column='abbrAddress', db_comment='지번 주소', max_length=128)),
                ('short_address', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), db_column='shortAddress', db_comment='간단 주소', size=10)),
            ],
            options={
                'db_table': 'raw_pet_kindergarden',
            },
        ),
        migrations.CreateModel(
            name='PetKindergarden',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='pet_kindergarden_id', db_comment='펫 유치원 아이디', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='유치원 이름', max_length=64)),
                ('main_thumbnail_url', models.URLField(db_comment='메인 썸네일')),
                ('profile_thumbnail_url', models.URLField(db_comment='프로필 썸네일 이미지')),
                ('phone_number', models.CharField(blank=True, db_comment='전화번호', max_length=16)),
                ('visible_phone_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), db_comment='노출 전화번호', size=2)),
                ('business_start_hour', models.TimeField(db_comment='영업 시작 시간')),
                ('business_end_hour', models.TimeField(db_comment='영업 종료 시간')),
                ('road_address', models.CharField(db_comment='도로명 주소', max_length=128)),
                ('abbr_address', models.CharField(db_comment='지번 주소', max_length=128)),
                ('detail_address', models.CharField(blank=True, db_comment='상세 주소', max_length=128)),
                ('short_address', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), db_comment='간단 주소', size=10)),
                ('guide_message', models.TextField(blank=True, db_comment='안내 메시지')),
                ('latitude', models.DecimalField(db_comment='위도', decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(db_comment='경도', decimal_places=6, max_digits=9)),
                ('point', django.contrib.gis.db.models.fields.PointField(db_comment='위치 좌표', srid=4326)),
                ('reservation_availability_option', models.CharField(choices=[('당일 예약 가능', 'SAME_DAY_AVAILABILITY'), ('당일 예약 불가', 'SAME_DAY_UNAVAILABILITY')], db_comment='예약 가능 설정', max_length=64)),
                ('reservation_change_option', models.CharField(choices=[('당일 변경 가능', 'SAME_DAY_CHANGE'), ('당일 변경 불가', 'SAME_DAY_UNCHANGE')], db_comment='예약 변경 설정', max_length=64)),
                ('daily_pet_limit', models.SmallIntegerField(db_comment='일일 펫 제한')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('user', models.ForeignKey(db_comment='유저 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='pet_kindergardens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pet_kindergarden',
            },
        ),
    ]
