# Generated by Django 4.2.11 on 2024-04-07 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_kindergardens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petkindergarden',
            name='user',
            field=models.ForeignKey(db_comment='유저 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='pet_kindergardens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='pet_kindergarden',
            field=models.ForeignKey(db_comment='펫 유치원 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='day_offs', to='pet_kindergardens.petkindergarden'),
        ),
    ]
