# Generated by Django 4.2.11 on 2024-04-07 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_id', db_comment='고객 아이디', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='고객 이름', max_length=32)),
                ('phone_number', models.CharField(db_comment='전화번호', max_length=16)),
                ('memo', models.TextField(blank=True, db_comment='메모')),
                ('is_active', models.BooleanField(db_comment='활성 여부', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerPet',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_pet_id', db_comment='고객 펫 아이디', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='반려동물 이름', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
            ],
            options={
                'db_table': 'customer_pet',
            },
        ),
        migrations.CreateModel(
            name='CustomerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_ticket_id', db_comment='고객 티켓 아이디', primary_key=True, serialize=False)),
                ('total_count', models.IntegerField(db_comment='총 횟수')),
                ('used_count', models.IntegerField(db_comment='사용 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('expired_at', models.DateTimeField(db_comment='만료 시간')),
                ('customer', models.ForeignKey(db_comment='고객 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_tickets', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_ticket',
            },
        ),
        migrations.CreateModel(
            name='CustomerTicketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_ticket_log_id', db_comment='고객 티켓 로그 아이디', primary_key=True, serialize=False)),
                ('reserved_at', models.DateTimeField(db_comment='예약 시간')),
                ('updated_reserved_at', models.DateTimeField(blank=True, db_comment='수정된 예약 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('customer_ticket', models.ForeignKey(db_comment='고객 티켓 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_ticket_logs', to='customers.customerticket')),
            ],
            options={
                'db_table': 'customer_ticket_log',
            },
        ),
    ]
