# Generated by Django 5.0.4 on 2024-05-07 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_kindergardens', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_id', db_comment='고객 아이디', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='고객 이름', max_length=32)),
                ('phone_number', models.CharField(db_comment='전화번호', max_length=16)),
                ('memo', models.TextField(blank=True, db_comment='메모')),
                ('is_active', models.BooleanField(db_comment='활성 여부', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('pet_kindergarden', models.ForeignKey(db_comment='펫 유치원 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='pet_kindergardens.petkindergarden')),
                ('user', models.ForeignKey(blank=True, db_comment='유저 아이디', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerPet',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_pet_id', db_comment='고객 펫 아이디', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='반려동물 이름', max_length=32)),
                ('is_deleted', models.BooleanField(db_comment='삭제 여부', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='삭제 시간', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('customer', models.ForeignKey(db_comment='고객 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_pets', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_pet',
            },
        ),
        migrations.CreateModel(
            name='CustomerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_ticket_id', db_comment='고객 티켓 아이디', primary_key=True, serialize=False)),
                ('expired_at', models.DateTimeField(db_comment='만료 시간')),
                ('total_count', models.IntegerField(db_comment='총 횟수')),
                ('used_count', models.IntegerField(db_comment='사용 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('customer', models.ForeignKey(db_comment='고객 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_tickets', to='customers.customer')),
                ('ticket', models.ForeignKey(db_comment='티켓 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_tickets', to='tickets.ticket')),
            ],
            options={
                'db_table': 'customer_ticket',
            },
        ),
        migrations.CreateModel(
            name='CustomerTicketReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_ticket_reservation_id', db_comment='고객 티켓 예약 아이디', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('customer_ticket', models.ForeignKey(db_comment='고객 티켓 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_ticket_reservations', to='customers.customerticket')),
            ],
            options={
                'db_table': 'customer_ticket_reservation',
            },
        ),
    ]
