# Generated by Django 4.2.11 on 2024-04-07 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_kindergardens', '0001_initial'),
        ('tickets', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticket',
            name='ticket',
            field=models.ForeignKey(db_comment='티켓 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_tickets', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='customerpet',
            name='customer',
            field=models.ForeignKey(db_comment='고객 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_pets', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pet_kindergarden',
            field=models.ForeignKey(db_comment='펫 유치원 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='pet_kindergardens.petkindergarden'),
        ),
    ]
