# Generated by Django 5.0.4 on 2024-05-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerticketreservation',
            name='reservation',
            field=models.ForeignKey(db_comment='예약 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_ticket_reservations', to='reservations.reservation'),
        ),
    ]
