# Generated by Django 5.0.6 on 2024-06-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('reservations', '0002_dailyreservation_pet_kindergarden'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTicketRegistrationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_ticket_registration_log_id', db_comment='고객 티켓 등록 로그 아이디', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('customer_ticket', models.ForeignKey(db_comment='고객 티켓 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_ticket_logs', to='customers.customerticket')),
            ],
            options={
                'db_table': 'customer_ticket_registration_log',
            },
        ),
        migrations.CreateModel(
            name='CustomerTicketUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='customer_ticket_usage_log_id', db_comment='고객 티켓 사용 로그 아이디', primary_key=True, serialize=False)),
                ('used_count', models.IntegerField(db_comment='사용한 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='수정 일시')),
                ('customer_ticket', models.ForeignKey(db_comment='고객 티켓 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_ticket_usage_logs', to='customers.customerticket')),
                ('reservation', models.ForeignKey(db_comment='예약 아이디', on_delete=django.db.models.deletion.CASCADE, related_name='customer_ticket_usage_logs', to='reservations.reservation')),
            ],
            options={
                'db_table': 'customer_ticket_usage_log',
            },
        ),
    ]
