# Generated by Django 4.2.11 on 2024-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpet',
            name='is_deleted',
            field=models.BooleanField(db_comment='삭제 여부', default=False),
        ),
    ]
