# Generated by Django 4.2.11 on 2024-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerpet_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_comment='삭제 일시', null=True),
        ),
    ]
